config/routes.rb
Rails.application.routes.draw do
  resources :bootcamps
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

root 'bootcamps#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bootcamp.rb
class Bootcamp < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bootcamps_controller.rb
class BootcampsController < ApplicationController
  before_action :set_bootcamp, only: %i[ show edit update destroy ]

  # GET /bootcamps or /bootcamps.json
  def index
    @bootcamps = Bootcamp.all
if params[:search].to_s != ''
    @bootcamps = Bootcamp.where("name LIKE '%#{params[:search]}%'")
  else
    @bootcamps = Bootcamp.all
  end
  end

  # GET /bootcamps/1 or /bootcamps/1.json
  def show
  end

  # GET /bootcamps/new
  def new
    @bootcamp = Bootcamp.new
  end

  # GET /bootcamps/1/edit
  def edit
  end

  # POST /bootcamps or /bootcamps.json
  def create
    @bootcamp = Bootcamp.new(bootcamp_params)

    respond_to do |format|
      if @bootcamp.save
        format.html { redirect_to bootcamp_url(@bootcamp), notice: "Bootcamp was successfully created." }
        format.json { render :show, status: :created, location: @bootcamp }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bootcamp.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /bootcamps/1 or /bootcamps/1.json
  def update
    respond_to do |format|
      if @bootcamp.update(bootcamp_params)
        format.html { redirect_to bootcamp_url(@bootcamp), notice: "Bootcamp was successfully updated." }
        format.json { render :show, status: :ok, location: @bootcamp }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bootcamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bootcamps/1 or /bootcamps/1.json
  def destroy
    @bootcamp.destroy

    respond_to do |format|
      format.html { redirect_to bootcamps_url, notice: "Bootcamp was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bootcamp
      @bootcamp = Bootcamp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bootcamp_params
      params.require(:bootcamp).permit(:name, :description, :dates, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootcamps_helper.rb
module BootcampsHelper
end

app/views/bootcamps/_bootcamp.html.erb
<div id="<%= dom_id bootcamp %>">
  <p>
    <strong>Name:</strong>
    <%= bootcamp.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= bootcamp.description %>
  </p>

  <p>
    <strong>Dates:</strong>
    <%= bootcamp.dates %>
  </p>
<p>
    <strong>Picture:</strong>
    <%= bootcamp.picture %>
  </p>

</div>

app/views/bootcamps/_form.html.erb
<%= form_with(model: bootcamp) do |form| %>
  <% if bootcamp.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bootcamp.errors.count, "error") %> prohibited this bootcamp from being saved:</h2>

      <ul>
        <% bootcamp.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :dates, style: "display: block" %>
    <%= form.text_field :dates %>
  </div>


 <div>
    <%= form.label :dates, style: "display: block" %>
    <%= form.file_field :picture %>
  </div>



  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/bootcamps/edit.html.erb
<h1>Editing bootcamp</h1>

<%= render "form", bootcamp: @bootcamp %>

<br>

<div>
  <%= link_to "Show this bootcamp", @bootcamp %> |
  <%= link_to "Back to bootcamps", bootcamps_path %>
</div>

app/views/bootcamps/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bootcamps</h1>

<div id="bootcamps">
  <% @bootcamps.each do |bootcamp| %>
    <%= render bootcamp %>
    <p>
      <%= link_to "Show this bootcamp", bootcamp %>
    </p>
  <% end %>
</div>

<%= link_to "New bootcamp", new_bootcamp_path %>

<h1>Search</h1>
<%= form_tag(bootcamps_path, method: "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Bootcamps" %>
  <%= submit_tag "Search Bootcamps"%>
<% end %>

<h1>Listing Bootcamps</h1>

app/views/bootcamps/new.html.erb
<h1>New bootcamp</h1>

<%= render "form", bootcamp: @bootcamp %>

<br>

<div>
  <%= link_to "Back to bootcamps", bootcamps_path %>
</div>

app/views/bootcamps/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bootcamp %>

<div>
  <%= link_to "Edit this bootcamp", edit_bootcamp_path(@bootcamp) %> |
  <%= link_to "Back to bootcamps", bootcamps_path %>

  <%= button_to "Destroy this bootcamp", @bootcamp, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>